import java_cup.runtime.*;

scan with {: return getScanner().next_token(); :};
terminal INT, STRING, SEMI, COMMA, ID, SPACE, EOFILE, FLOAT, NEWLINE;
non terminal prog, stmt, decln, varlist, type, s, progstmt;
s ::= prog {: System.out.println("Valid declaration"); :}
EOFILE {: System.exit(0); :};
prog ::= progstmt | stmt;
stmt ::= decln;
decln ::= type SPACE varlist SEMI;
type ::= INT | SPACE;
varlist ::= ID COMMA varlist | ID; 